---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: birds-app-back-end-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: birds-app-back-end-ripleymj
  template:
    metadata:
      labels:
        app: birds-app-back-end-ripleymj
    spec:
      containers:
        - image: 'ghcr.io/ripleymj/birds-app-back-end:a7d1283f9e0829bd7263819576b89e87ac0b88ee'
          name: birds-back-front-end
          ports:
            - containerPort: 8080
