---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: birds-app-back-end-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: birds-app-back-end-ripleymj
  template:
    metadata:
      labels:
        app: birds-app-back-end-ripleymj
    spec:
      containers:
        - image: 'ghcr.io/ripleymj/birds-app-back-end:b08e41e451c1d40ff6d49a33e0cf78c0d8e2edce'
          name: birds-back-front-end
          ports:
            - containerPort: 8080
