---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uug-demo-api
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: uug-demo-api
  template:
    metadata:
      labels:
        app: uug-demo-api
    spec:
      containers:
        - image: 'ghcr.io/ripleymj/uug-demo-api:adf0eee46cb7675eea872be0f77bfa6472fe31b7'
          name: uug-demo-api
          ports:
            - containerPort: 3000
