---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: birds-app-front-end-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: birds-app-front-end-ripleymj
  template:
    metadata:
      labels:
        app: birds-app-front-end-ripleymj
    spec:
      containers:
        - image: 'ghcr.io/ripleymj/birds-app-front-end:ef92e34a3070b5a82714e7d95db9e8968112c20c'
          name: birds-app-front-end
          ports:
            - containerPort: 80
