# Move binary to final image and run it
FROM alpine:latest

WORKDIR /app

# Copy built binary from build image
COPY back-end/app .
COPY back-end/birds.json .

# Expose port 3000
EXPOSE 3000

CMD ["./app"]
